"""A verified MCP tool surface, exported as a tooltrace-bench task pack.

This project answers "is this tool surface sound?". It cannot answer "will an
agent use it correctly?" — that is a measurement over agents, and the sibling
project [tooltrace-bench](https://github.com/webdevsamran/tooltrace-bench) is
the one that makes it. The hand-off is this module.

## What a generated task actually measures

For each tool in the manifest: given the declared contract, write the arguments
for one call to it. The task is graded with the **tool's own `inputSchema`** as
the scorer — `json_schema`, one of tooltrace-bench's built-in assertion types,
pointed at the schema this project just verified.

That is the whole idea, and it is why the hand-off is worth having rather than
being two tools in the same README. A tool manifest exists so a caller can
construct a valid call from it. Whether an agent can is a fact about the agent,
measured against the contract instead of against somebody's opinion of it.

## Three things the export refuses to do

**Export a surface that did not pass.** A pack built from a manifest this tool
reports errors on would be benchmarking agents against a contract we say is
broken, and every failure would be ambiguous between the agent and the
manifest. `--allow-findings` overrides it, and records the findings in the pack
so the ambiguity is at least written down.

**Export a tool whose description was flagged as poisoning.** You cannot ask an
agent to follow a description that is an injection and then score it for
compliance: the correct behaviour is to refuse, and the task would mark that
wrong. Measuring *resistance* is a different task shape, and pretending this one
does it would be worse than not shipping it. `--include-flagged` exports them
with the rule id attached, for an author writing that other shape by hand.

**Export a task nothing can fail.** A tool declaring `{"type": "object",
"properties": {}}` constrains nothing: `{}` validates, and so does anything
else. A task whose assertion every submission passes is not a measurement, and a
pack full of them reports a score that means nothing. Those are skipped, and the
reason travels in the pack's README.

## Every task carries a reference solution

`tooltrace task test` refuses a task with no `metadata.scripted_script`: without
one, nobody has shown the task is solvable, and an unsolvable task in a
benchmark is a score everybody loses for the author's reason. That objection is
this project's own ethic arriving from the other side, so it is honoured rather
than worked around.

The solution is generated by `apiverity.fuzz.generate.generate_valid` — the
same generator `apiverity test` uses — over the same schema the assertion
grades against. Not a second implementation: a schema-to-example generator
written here would be a parallel version of one this project already ships, and
the two would disagree eventually.

Seeded from the tool's name, so re-running the export produces the same pack
byte for byte.

## Why this writes files rather than importing tooltrace-bench

An exporter that imported the sibling project would make it a dependency of this
one, and would couple this project's release to theirs. The output is YAML held
against `schemas/vendor/tooltrace-task-*.schema.json` — their published schema,
vendored the way the OAI's Arazzo schema is.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

#: Assertion types used here. Every one is a built-in scorer in the published
#: tooltrace-bench; a task naming a scorer that does not exist is a task that
#: cannot run, and inventing one to make an export look richer would be exactly
#: that.
ASSERTIONS = ("file_exists", "json_schema")

#: The tools the agent is given. File tools only: the task is to write a call
#: payload, and network or shell access would widen the surface being measured
#: without widening what is being asked.
ALLOWED_TOOLS = ("read_file", "write_file", "list_directory")

#: Where the agent writes its answer.
ANSWER = "call.json"

#: The manifest, placed in the workspace so the agent reads the contract rather
#: than a paraphrase of it.
MANIFEST = "tools.json"

#: Rules that make a description unusable as a task instruction. Named rather
#: than pattern-matched on the prefix so adding an `MCP-POISON-*` rule is a
#: decision about this export, not a silent change to it.
POISONING_RULES = frozenset(
    {
        "MCP-POISON-INSTRUCTION",
        "MCP-POISON-CREDENTIAL-PATH",
        "MCP-POISON-INVISIBLE-TEXT",
        "MCP-POISON-HIDDEN-MARKUP",
        "MCP-POISON-CROSS-TOOL",
    }
)


class ExportError(Exception):
    """A surface this will not turn into a benchmark."""


@dataclass(frozen=True)
class Skipped:
    """A tool that produced no task, and why."""

    name: str
    reason: str


@dataclass
class Pack:
    """The task pack, before it is written."""

    name: str
    tasks: list[dict[str, Any]] = field(default_factory=list)
    skipped: list[Skipped] = field(default_factory=list)
    findings: list[dict[str, Any]] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "pack": self.name,
            "tasks": [task["id"] for task in self.tasks],
            "task_count": len(self.tasks),
            "skipped": [{"tool": s.name, "reason": s.reason} for s in self.skipped],
        }


def constrains_anything(schema: Any) -> bool:
    """Whether a submission can fail validation against this schema.

    An object schema with no `required`, no declared properties and no
    `additionalProperties: false` accepts `{}` and accepts everything else.
    Grading against it is not grading.
    """
    if not isinstance(schema, dict):
        return False
    if schema.get("required"):
        return True
    if schema.get("additionalProperties") is False:
        return True
    properties = schema.get("properties")
    if isinstance(properties, dict) and properties:
        # A declared property with a type or a constraint can be violated by a
        # submission that includes it wrongly. One with an empty schema cannot.
        return any(isinstance(sub, dict) and sub for sub in properties.values())
    for keyword in ("oneOf", "anyOf", "allOf", "not", "minProperties", "patternProperties"):
        if schema.get(keyword):
            return True
    return False


def _slug(name: str) -> str:
    kept = [c if c.isalnum() or c in "._-" else "-" for c in name.lower()]
    return "".join(kept).strip("-") or "tool"


def _flagged(findings: list[Any]) -> dict[str, list[str]]:
    """`{tool name: [rule ids]}` for descriptions reported as poisoning."""
    out: dict[str, list[str]] = {}
    for finding in findings:
        rule_id = getattr(finding, "rule_id", "")
        if rule_id not in POISONING_RULES:
            continue
        # The operation key for an MCP tool is `tool <name>`; the bare name is
        # accepted too so a change there does not silently stop flagging.
        key = str(getattr(finding, "operation_key", "") or "")
        name = key.split(" ", 1)[1] if key.startswith("tool ") else key
        if name:
            out.setdefault(name, []).append(rule_id)
    return out


def _objective(tool: dict[str, Any]) -> str:
    description = str(tool.get("description") or "").strip()
    said = f" The tool says: {description}" if description else ""
    return (
        f"Read {MANIFEST} and write {ANSWER}: a JSON object holding the arguments for a "
        f"single call to the `{tool['name']}` tool.{said} Use only the fields its "
        "inputSchema declares, and satisfy every constraint it states."
    )


def reference_solution(node: Any, name: str) -> Any:
    """A conformant call payload, from this project's own generator.

    `apiverity test` already turns a schema into a valid instance; writing a
    second one here would be a parallel implementation of something this
    project ships, and the two would disagree eventually. Seeded from the tool
    name so the export is reproducible.
    """
    import random

    from apiverity.fuzz.generate import generate_valid

    return generate_valid(node, random.Random(f"agent-tasks:{name}"))


def _task(
    pack: str,
    tool: dict[str, Any],
    manifest_text: str,
    *,
    provenance: dict[str, Any],
    flagged: list[str],
    solution: Any = None,
) -> dict[str, Any]:
    schema = tool["inputSchema"]
    name = str(tool["name"])
    task: dict[str, Any] = {
        "schema_version": 1,
        "id": f"{pack}/{_slug(name)}",
        "name": f"Call {name}",
        "version": "1.0.0",
        "category": "tool-use",
        "difficulty": "easy" if len(schema.get("required") or []) <= 1 else "medium",
        "tags": ["api-verity-lab", "mcp", "tool-use"],
        "objective": _objective(tool),
        "description": (
            f"The manifest in {MANIFEST} is the contract. `{name}` declares this "
            f"inputSchema:\n\n{json.dumps(schema, indent=2)}\n\n"
            f"Write {ANSWER} containing one JSON object of arguments for it."
        ),
        "starting_workspace": {MANIFEST: manifest_text},
        "allowed_tools": list(ALLOWED_TOOLS),
        "assertions": [
            {
                "type": "file_exists",
                "params": {"path": ANSWER},
                "weight": 0.5,
                "description": f"{ANSWER} was written",
            },
            {
                # The contract grades the answer. Not a hand-written expected
                # value: a rubric somebody typed can disagree with the schema
                # the service actually publishes, and then the benchmark is
                # measuring the rubric.
                "type": "json_schema",
                "params": {"path": ANSWER, "schema": schema},
                "weight": 1.0,
                "description": f"arguments satisfy {name}'s declared inputSchema",
            },
        ],
        "timeout_seconds": 120,
        "max_steps": 8,
        "network_policy": "disabled",
        # `mcp_tool`, not `tool`: `tool` in the provenance block is the
        # *generating* tool, and overwriting it with the MCP tool's name made
        # the pack claim it had been generated by `search_orders`.
        "metadata": {"source": dict(provenance, mcp_tool=name)},
    }
    if solution is not None:
        # A reference solution, in the shape `tooltrace task test` runs: a
        # scripted agent that writes the answer. Without one the sibling tool
        # reports the task as unproven, and it is right to.
        task["metadata"]["scripted_script"] = [
            {
                "tool": "write_file",
                "args": {"path": ANSWER, "content": json.dumps(solution, sort_keys=True)},
            }
        ]
    if flagged:
        # Carried, not hidden. An author writing a resistance task needs to know
        # which rule fired and on what.
        task["metadata"]["source"]["poisoning_rules"] = sorted(flagged)
        task["tags"].append("flagged-description")
    return task


def _modelled(service: Any) -> dict[str, Any]:
    """`{tool name: SchemaNode}` for each operation's request body."""
    out: dict[str, Any] = {}
    for operation in getattr(service, "operations", []):
        key = str(getattr(operation, "key", "") or "")
        name = key.split(" ", 1)[1] if key.startswith("tool ") else key
        body = getattr(operation, "request_body", None)
        content = getattr(body, "content", None) or {}
        node = content.get("application/json")
        if name and node is not None:
            out[name] = node
    return out


def build(
    manifest: dict[str, Any],
    findings: list[Any],
    *,
    pack: str,
    provenance: dict[str, Any],
    service: Any = None,
    include_flagged: bool = False,
) -> Pack:
    """Turn a verified manifest into a pack of tasks."""
    from apiverity.specs.mcp.manifest import unwrap_manifest

    tools, _envelope = unwrap_manifest(manifest)
    modelled = _modelled(service) if service is not None else {}
    manifest_text = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    flagged = _flagged(findings)

    built = Pack(name=pack)
    for entry in tools:
        if not isinstance(entry, dict):
            continue
        name = str(entry.get("name") or "")
        if not name:
            continue
        schema = entry.get("inputSchema")
        if not isinstance(schema, dict):
            built.skipped.append(Skipped(name, "declares no inputSchema, so nothing grades a call"))
            continue
        if not constrains_anything(schema):
            built.skipped.append(
                Skipped(
                    name,
                    "its inputSchema constrains nothing, so every submission passes and the "
                    "task measures nothing",
                )
            )
            continue
        rules = flagged.get(name, [])
        if rules and not include_flagged:
            built.skipped.append(
                Skipped(
                    name,
                    f"its description was reported as poisoning ({', '.join(sorted(rules))}); "
                    "the correct behaviour is to refuse it, which this task shape would score "
                    "as a failure. Re-run with --include-flagged to export it anyway",
                )
            )
            continue
        node = modelled.get(name)
        built.tasks.append(
            _task(
                pack,
                dict(entry, inputSchema=schema),
                manifest_text,
                provenance=provenance,
                flagged=rules,
                solution=reference_solution(node, name) if node is not None else None,
            )
        )

    if not built.tasks:
        raise ExportError(
            "no tool in this manifest produces a task that can be failed. "
            + "; ".join(f"{s.name}: {s.reason}" for s in built.skipped)
        )
    return built


# -- writing -------------------------------------------------------------


def _yaml(task: dict[str, Any]) -> str:
    """Dump with literal blocks for multi-line strings.

    The default representer emits a double-quoted scalar with every newline
    escaped, which turns an embedded manifest into one unreadable line. A task
    pack is read by the person deciding whether to trust it, so the readable
    form is the correct one.
    """
    import yaml

    class _Dumper(yaml.SafeDumper):
        pass

    def _string(dumper: yaml.SafeDumper, value: str) -> yaml.ScalarNode:
        if "\n" in value:
            return dumper.represent_scalar("tag:yaml.org,2002:str", value, style="|")
        return dumper.represent_scalar("tag:yaml.org,2002:str", value)

    _Dumper.add_representer(str, _string)
    return yaml.dump(task, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=100)


def readme(built: Pack, provenance: dict[str, Any]) -> str:
    """The pack's own account of where it came from and what is missing.

    A generated benchmark with no provenance is a benchmark nobody can check,
    and the skipped list matters more than the exported one: a reader comparing
    tool count to task count will otherwise assume the difference was an error.
    """
    lines = [
        f"# {built.name}",
        "",
        "Generated by `apiverity agent-tasks` from a verified MCP tool manifest.",
        "Do not edit by hand: re-run the command.",
        "",
        "| | |",
        "|---|---|",
        f"| Manifest | `{provenance.get('manifest')}` |",
        f"| Contract hash | `{provenance.get('contract_hash')}` |",
        f"| Generated by | api-verity-lab {provenance.get('tool_version')} |",
        f"| Tasks | {len(built.tasks)} |",
        "",
        "## What each task measures",
        "",
        "Given the manifest, write the arguments for one call to a tool. The tool's own",
        "`inputSchema` is the scorer -- a `json_schema` assertion pointed at the schema",
        "this project verified. A tool manifest exists so a caller can construct a valid",
        "call from it; whether an agent can is a fact about the agent, measured against",
        "the contract rather than against somebody's opinion of it.",
        "",
    ]
    if built.findings:
        lines += [
            "## This surface did not pass",
            "",
            "Exported with `--allow-findings`. Every failure below is ambiguous between the",
            "agent and the manifest, and that ambiguity is this pack's, not the agent's.",
            "",
        ]
        lines += [f"- `{f['rule_id']}` ({f['severity']}) {f['message']}" for f in built.findings]
        lines.append("")
    if built.skipped:
        lines += ["## Tools with no task, and why", ""]
        lines += [f"- **{s.name}** — {s.reason}" for s in built.skipped]
        lines.append("")
    return "\n".join(lines)


def write(built: Pack, directory: str | Path, provenance: dict[str, Any]) -> list[Path]:
    target = Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for task in built.tasks:
        path = target / (task["id"].split("/", 1)[1] + ".yaml")
        path.write_text(_yaml(task), encoding="utf-8", newline="\n")
        written.append(path)
    index = target / "README.md"
    index.write_text(readme(built, provenance), encoding="utf-8", newline="\n")
    written.append(index)
    return written


__all__ = [
    "ALLOWED_TOOLS",
    "ANSWER",
    "ASSERTIONS",
    "MANIFEST",
    "POISONING_RULES",
    "ExportError",
    "Pack",
    "Skipped",
    "build",
    "constrains_anything",
    "readme",
    "reference_solution",
    "write",
]
