"""Render docs/compliance-mapping.md from the mapping in the code.

The published mapping between OWASP controls and this project's rules is the
kind of document that rots invisibly: a rule gets renamed, the code keeps
working, and the table in the docs quietly promises coverage that no longer
exists. So the table is generated, and CI fails when the committed copy and the
code disagree.

    python scripts/generate_compliance_map.py            # write
    python scripts/generate_compliance_map.py --check    # fail if stale
"""

from __future__ import annotations

import pathlib
import sys

# `scripts/` so `page_meta` resolves, the repository root so `apiverity`
# does. Running this as a script puts the first one on the path; loading
# it by file location -- which is how the tests load it -- puts neither.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from page_meta import front_matter

from apiverity.reports.compliance import FRAMEWORKS, producing_commands

TARGET = pathlib.Path(__file__).resolve().parents[1] / "docs" / "compliance-mapping.md"

_HEADER = """\
# Compliance mapping

<!-- Generated by scripts/generate_compliance_map.py -- do not edit by hand. -->

Findings from this tool, mapped onto three published frameworks. Render one for
any result bundle:

```bash
apiverity report ./bundle --format owasp-mcp
apiverity report ./bundle --format owasp-asi
apiverity report ./bundle --format owasp-api
```

Every control appears in every rendered report, including the ones this tool
cannot assess. A mapping report that lists only the controls it hit reads as a
clean bill of health for the rest, and that is the easiest way for a governance
tool to mislead the person relying on it.

**The control names and numbering below are quoted from the published
frameworks. The mapping to this project's rules is api-verity-lab's own reading
and is not endorsed by OWASP.** A control with rules listed is one this tool
can produce evidence for; it is not a claim that the evidence is sufficient.

"""

_LEGEND = """\
## How a rendered report grades a control

| State | Meaning |
|---|---|
| Findings | this run produced evidence against the control |
| Assessed, clear | rules mapped to the control ran in this artifact and found nothing |
| Not exercised by this run | rules exist, but the command that wrote the artifact does not produce them |
| Not assessable by this tool | nothing this tool can see speaks to the control; the reason is printed |

The third state is the one that matters. Without it, "no findings" means both
*checked and clean* and *never looked at*, which is precisely the ambiguity an
audit exists to remove.
"""


def render() -> str:
    out = [front_matter("compliance-mapping.md") + _HEADER]
    for framework in FRAMEWORKS.values():
        out.append(f"## {framework.name} {framework.version}\n")
        out.append(
            f"Source: <{framework.url}>"
            f"{', published ' + framework.published if framework.published else ''}. "
            f"Read {framework.read_on}.\n"
        )
        out.append("| # | Control | Rules | Produced by |")
        out.append("|---|---|---|---|")
        for control in framework.controls:
            if control.rules:
                rules = "<br>".join(f"`{prefix}`" for prefix in control.rules)
                commands = sorted(
                    {cmd for prefix in control.rules for cmd in producing_commands(prefix)}
                )
                produced = ", ".join(f"`{cmd}`" for cmd in commands) or "--"
            else:
                rules = "*not assessable*"
                produced = "--"
            out.append(f"| {control.id} | {control.title} | {rules} | {produced} |")
        out.append("")

        limits = [c for c in framework.controls if c.limitation]
        if limits:
            out.append("### What this tool cannot see\n")
            for control in limits:
                out.append(f"- **{control.id} {control.title}** — {control.limitation}")
            out.append("")

        caveats = [c for c in framework.controls if c.caveat]
        if caveats:
            out.append("### Where the coverage is partial\n")
            for control in caveats:
                out.append(f"- **{control.id} {control.title}** — {control.caveat}")
            out.append("")

    out.append(_LEGEND)
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    rendered = render()
    previous = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else None
    if previous == rendered:
        print(f"ok     {TARGET.name}")
        return 0
    if "--check" in sys.argv:
        print(
            "error: docs/compliance-mapping.md is stale; run scripts/generate_compliance_map.py",
            file=sys.stderr,
        )
        return 1
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote  {TARGET.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
