"""Render docs/rule-catalog.md from the code's rule catalog.

The hand-maintained version had drifted badly: it documented six rule IDs
that do not exist (BRK-DEPRECATED, BRK-FIELD-REQUIRED-REQUEST,
BRK-FIELD-REMOVED-RESPONSE, BRK-TYPE-CHANGED-RESPONSE, BRK-SEC-ADDED,
BRK-SEC-REMOVED) and omitted twenty-three that do. Anyone configuring a
severity override from the docs would have used an ID the engine ignores.

Generating it means the document and `apiverity rules` cannot disagree.
Run after changing CATALOG; `--check` fails if the committed file is stale.
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from apiverity.rules.breaking import CATALOG

_HEADER = """\
# Breaking-Rule Catalog

<!-- Generated by scripts/generate_rule_catalog.py -- do not edit by hand. -->

Severity levels: **ERROR** (blocks CI), **WARN** (risky, review), **INFO**
(informational). Rules are *direction-aware*: the same schema edit can be safe
in a request and breaking in a response. Override any severity with
`apiverity breaking --severity-override <RULE-ID>=WARN` or in config, and list
the live catalog at any time with `apiverity rules --json`.

"""

#: (title, rule-id prefixes, note). The note renders under the heading.
#:
#: The note slot exists for the MCP family. That taxonomy is this project's own
#: -- upstream MCP defines no breaking-change semantics for a tool manifest --
#: and saying so only in a source comment would leave the published catalogue
#: implying a standard that does not exist. Groups with no caveat pass "".
_GROUPS: list[tuple[str, tuple[str, ...], str]] = [
    ("Operations and RPCs", ("BRK-OP-", "BRK-RPC-"), ""),
    ("Parameters", ("BRK-PARAM-",), ""),
    ("Request bodies and fields", ("BRK-REQ-",), ""),
    ("Responses", ("BRK-RESP-", "BRK-HEADER-"), ""),
    ("Schemas and constraints", ("BRK-CONSTRAINT-", "BRK-ENUM-", "BRK-MEDIA-"), ""),
    ("Lifecycle and security", ("BRK-DEPRECATION-", "BRK-SECURITY-"), ""),
    (
        "MCP tool manifests",
        ("BRK-MCP-",),
        "The Model Context Protocol defines no breaking-change semantics for a tool "
        "manifest: tools carry no version field, and SEP-1575 *Tool Semantic "
        "Versioning* is an open, unsponsored proposal. **This taxonomy is "
        "api-verity-lab's own and is not blessed by the MCP specification.**\n\n"
        "Only changes the shared engine cannot already see are listed here. A removed "
        "tool, a newly-required argument or a narrowed enum fires the same "
        "`BRK-RPC-REMOVED`, `BRK-PARAM-ADDED-REQUIRED` and `BRK-ENUM-NARROWED-REQUEST` "
        "rules as every other protocol, because an MCP manifest compiles into the same "
        "contract model.",
    ),
]


def render() -> str:
    remaining = dict(sorted(CATALOG.items()))
    out = [_HEADER]
    for title, prefixes, note in _GROUPS:
        rows = [
            spec
            for rule_id, spec in list(remaining.items())
            if rule_id.startswith(prefixes) and remaining.pop(rule_id, None) is not None
        ]
        if not rows:
            continue
        out.append(f"## {title}\n")
        if note:
            out.append(f"{note}\n")
        out.append("| Rule | Severity | Fires when |")
        out.append("|---|---|---|")
        for spec in rows:
            out.append(f"| `{spec.rule_id}` | {spec.severity.value.upper()} | {spec.description} |")
        out.append("")
    if remaining:
        out.append("## Other\n")
        out.append("| Rule | Severity | Fires when |")
        out.append("|---|---|---|")
        for spec in remaining.values():
            out.append(f"| `{spec.rule_id}` | {spec.severity.value.upper()} | {spec.description} |")
        out.append("")
    out.append(f"_{len(CATALOG)} rules._\n")
    return "\n".join(out)


def main() -> int:
    target = pathlib.Path(__file__).resolve().parents[1] / "docs" / "rule-catalog.md"
    rendered = render()
    previous = target.read_text(encoding="utf-8") if target.is_file() else None
    if previous == rendered:
        print(f"ok     {target.name} ({len(CATALOG)} rules)")
        return 0
    if "--check" in sys.argv:
        print(
            "error: docs/rule-catalog.md is stale; run scripts/generate_rule_catalog.py",
            file=sys.stderr,
        )
        return 1
    target.write_text(rendered, encoding="utf-8")
    print(f"wrote  {target.name} ({len(CATALOG)} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
